//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/InputS/HighlightTestInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputS/HighlightTestInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @HighlightTestInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @HighlightTestInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HighlightTestInput"",
    ""maps"": [
        {
            ""name"": ""HighlightSelector"",
            ""id"": ""6c1113f8-015d-4f23-938e-aca155b3a79d"",
            ""actions"": [
                {
                    ""name"": ""Single"",
                    ""type"": ""Button"",
                    ""id"": ""c4d91e2a-4154-4e76-95d3-447a5878f9e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Square"",
                    ""type"": ""Button"",
                    ""id"": ""41fa8673-b92f-464f-b160-ec493bd7aaf5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Circle"",
                    ""type"": ""Button"",
                    ""id"": ""c5c2a1ec-dd27-4110-a731-66f9ffcaa898"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line"",
                    ""type"": ""Button"",
                    ""id"": ""b88e5eff-b32b-4183-8bac-46957329aa5e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cone"",
                    ""type"": ""Button"",
                    ""id"": ""88d8baa6-6af0-40e5-af7e-234df5a9e061"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d498b7e7-c3e1-41a4-a85c-9b2e14ef4d1b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Single"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33733eee-4861-46d6-8c4c-d5e3c43fdb8e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7428ccbc-81cb-4076-a41f-02e9307e16c4"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a3c286e-d85d-4232-b7fb-483793cfecca"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1feeda46-be80-4819-a8bc-c590c48d4692"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // HighlightSelector
        m_HighlightSelector = asset.FindActionMap("HighlightSelector", throwIfNotFound: true);
        m_HighlightSelector_Single = m_HighlightSelector.FindAction("Single", throwIfNotFound: true);
        m_HighlightSelector_Square = m_HighlightSelector.FindAction("Square", throwIfNotFound: true);
        m_HighlightSelector_Circle = m_HighlightSelector.FindAction("Circle", throwIfNotFound: true);
        m_HighlightSelector_Line = m_HighlightSelector.FindAction("Line", throwIfNotFound: true);
        m_HighlightSelector_Cone = m_HighlightSelector.FindAction("Cone", throwIfNotFound: true);
    }

    ~@HighlightTestInput()
    {
        UnityEngine.Debug.Assert(!m_HighlightSelector.enabled, "This will cause a leak and performance issues, HighlightTestInput.HighlightSelector.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HighlightSelector
    private readonly InputActionMap m_HighlightSelector;
    private List<IHighlightSelectorActions> m_HighlightSelectorActionsCallbackInterfaces = new List<IHighlightSelectorActions>();
    private readonly InputAction m_HighlightSelector_Single;
    private readonly InputAction m_HighlightSelector_Square;
    private readonly InputAction m_HighlightSelector_Circle;
    private readonly InputAction m_HighlightSelector_Line;
    private readonly InputAction m_HighlightSelector_Cone;
    /// <summary>
    /// Provides access to input actions defined in input action map "HighlightSelector".
    /// </summary>
    public struct HighlightSelectorActions
    {
        private @HighlightTestInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public HighlightSelectorActions(@HighlightTestInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "HighlightSelector/Single".
        /// </summary>
        public InputAction @Single => m_Wrapper.m_HighlightSelector_Single;
        /// <summary>
        /// Provides access to the underlying input action "HighlightSelector/Square".
        /// </summary>
        public InputAction @Square => m_Wrapper.m_HighlightSelector_Square;
        /// <summary>
        /// Provides access to the underlying input action "HighlightSelector/Circle".
        /// </summary>
        public InputAction @Circle => m_Wrapper.m_HighlightSelector_Circle;
        /// <summary>
        /// Provides access to the underlying input action "HighlightSelector/Line".
        /// </summary>
        public InputAction @Line => m_Wrapper.m_HighlightSelector_Line;
        /// <summary>
        /// Provides access to the underlying input action "HighlightSelector/Cone".
        /// </summary>
        public InputAction @Cone => m_Wrapper.m_HighlightSelector_Cone;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_HighlightSelector; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="HighlightSelectorActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(HighlightSelectorActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="HighlightSelectorActions" />
        public void AddCallbacks(IHighlightSelectorActions instance)
        {
            if (instance == null || m_Wrapper.m_HighlightSelectorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HighlightSelectorActionsCallbackInterfaces.Add(instance);
            @Single.started += instance.OnSingle;
            @Single.performed += instance.OnSingle;
            @Single.canceled += instance.OnSingle;
            @Square.started += instance.OnSquare;
            @Square.performed += instance.OnSquare;
            @Square.canceled += instance.OnSquare;
            @Circle.started += instance.OnCircle;
            @Circle.performed += instance.OnCircle;
            @Circle.canceled += instance.OnCircle;
            @Line.started += instance.OnLine;
            @Line.performed += instance.OnLine;
            @Line.canceled += instance.OnLine;
            @Cone.started += instance.OnCone;
            @Cone.performed += instance.OnCone;
            @Cone.canceled += instance.OnCone;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="HighlightSelectorActions" />
        private void UnregisterCallbacks(IHighlightSelectorActions instance)
        {
            @Single.started -= instance.OnSingle;
            @Single.performed -= instance.OnSingle;
            @Single.canceled -= instance.OnSingle;
            @Square.started -= instance.OnSquare;
            @Square.performed -= instance.OnSquare;
            @Square.canceled -= instance.OnSquare;
            @Circle.started -= instance.OnCircle;
            @Circle.performed -= instance.OnCircle;
            @Circle.canceled -= instance.OnCircle;
            @Line.started -= instance.OnLine;
            @Line.performed -= instance.OnLine;
            @Line.canceled -= instance.OnLine;
            @Cone.started -= instance.OnCone;
            @Cone.performed -= instance.OnCone;
            @Cone.canceled -= instance.OnCone;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="HighlightSelectorActions.UnregisterCallbacks(IHighlightSelectorActions)" />.
        /// </summary>
        /// <seealso cref="HighlightSelectorActions.UnregisterCallbacks(IHighlightSelectorActions)" />
        public void RemoveCallbacks(IHighlightSelectorActions instance)
        {
            if (m_Wrapper.m_HighlightSelectorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="HighlightSelectorActions.AddCallbacks(IHighlightSelectorActions)" />
        /// <seealso cref="HighlightSelectorActions.RemoveCallbacks(IHighlightSelectorActions)" />
        /// <seealso cref="HighlightSelectorActions.UnregisterCallbacks(IHighlightSelectorActions)" />
        public void SetCallbacks(IHighlightSelectorActions instance)
        {
            foreach (var item in m_Wrapper.m_HighlightSelectorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HighlightSelectorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="HighlightSelectorActions" /> instance referencing this action map.
    /// </summary>
    public HighlightSelectorActions @HighlightSelector => new HighlightSelectorActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "HighlightSelector" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="HighlightSelectorActions.AddCallbacks(IHighlightSelectorActions)" />
    /// <seealso cref="HighlightSelectorActions.RemoveCallbacks(IHighlightSelectorActions)" />
    public interface IHighlightSelectorActions
    {
        /// <summary>
        /// Method invoked when associated input action "Single" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSingle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Square" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSquare(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Circle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCircle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Line" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLine(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Cone" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCone(InputAction.CallbackContext context);
    }
}
